behaviors:
  RacerAI:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 40960
      learning_rate: 0.0002
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 5000000
    time_horizon: 256
    summary_freq: 5000
    threaded: true
    checkpoint_interval: 250000
    keep_checkpoints: 5

env_settings:
  env_path: C:\RacerAI\RacerTrainer.exe
  base_port: 5005
  num_envs: 14
  seed: -1

engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 20.0
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: true

checkpoint_settings:
  run_id: 
  results_dir: C:\RacerAI_Results
  initialize_from: null
  load_model: false
  train_model: true
  inference: false
