behaviors:
  RacerAI:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 40960
      learning_rate: 1.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 4
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 15000000         
    time_horizon: 64
    summary_freq: 1000
    checkpoint_interval: 100000

env_settings:
  env_path: "C:\\RacerAI\\RacerTrainer.exe"
  base_port: 5005
  num_envs: 10
  seed: -1

engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 20.0
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: true             # Set to false if you want visuals

checkpoint_settings:
  run_id: RacerAI_15M_Run
  initialize_from: null
  load_model: false
  resume: false
  force: false
  train_model: true
  inference: false
  results_dir: "C:\\RacerAI_Results"